language: r
cache:
  packages: yes
pandoc_version: 1.19.2.1

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0
  matrix:
    - PANDOC_VERSION=default
    - PANDOC_VERSION=latest PATH=$HOME/bin:$PATH

before_install:
  - "[[ ${PANDOC_VERSION} = latest ]] && ./tools/install-pandoc.sh || true"
  - tlmgr install units

matrix:
  include:
  - r: release
    env: rlang='CRAN'
    before_deploy:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    after_success:
    - nvm install stable
    - npm install netlify-cli -g
    - Rscript -e 'pkgdown::build_site(".", document = FALSE, preview = FALSE, ...)'
    deploy:
      provider: script
      script: netlify deploy --prod --dir _docs
      skip_cleanup: true
