language: r
cache:
  packages: yes
pandoc_version: 1.19.2.1

env:
  - NETLIFY_SITE_ID=5d77c13c-e2ee-4a31-87ca-2fe657196160
  # NETLIFY_AUTH_TOKEN set in travis settings
  global:
    - _R_CHECK_TESTS_NLINES_=0
  matrix:
    - PANDOC_VERSION=default
    - PANDOC_VERSION=latest PATH=$HOME/bin:$PATH

before_install:
  - "[[ ${PANDOC_VERSION} = latest ]] && ./tools/install-pandoc.sh || true"
  - tlmgr install units

r_github_packages:
  - r-lib/pkgdown

matrix:
  include:
  - r: release
    env: rlang='CRAN'
    after_success:
    - nvm install stable
    - npm install netlify-cli -g
    - Rscript -e 'pkgdown::build_site(".", document = FALSE, preview = FALSE, ...)'
    deploy:
      provider: script
      script: netlify deploy --prod --dir docs
      skip_cleanup: true
